name: job_seeker_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7  # 添加 SVG 支持库
  get: ^4.7.2
  dio: ^5.4.0  # HTTP 请求库
  shared_preferences: ^2.2.2  # 本地存储，用于保存令牌
  json_annotation: ^4.8.1  # JSON 序列化支持
  image_picker: ^1.1.2
  socket_io_client: ^1.0.2  # 使用支持空安全且与 Socket.IO v2.x 服务器兼容的版本
  intl: ^0.19.0  # 国际化和日期时间格式化
  pull_to_refresh: ^2.0.0  # 下拉刷新和上拉加载更多控件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/  # 配置资源路径
